### ISSUE TITLE
Unparseable date Exception for ODT doc

### ISSUE THREAD

**Issue by florianajir** [harvard-lts/fits#16]
The analysis of an odt file throw this kind of exception :

$ ./fits.sh -i ~/Documents/fiche_version_asalae_1.4_encoursredac.odt 

java.text.ParseException: Unparseable date: "PT16H47M"
    at java.text.DateFormat.parse(DateFormat.java:357)
    at nz.govt.natlib.adapter.openoffice.OpenOfficeAdapter$MetadataHandler.endElement(OpenOfficeAdapter.java:246)
    at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
    at nz.govt.natlib.adapter.openoffice.OpenOfficeAdapter.processMetadata(OpenOfficeAdapter.java:135)
    at nz.govt.natlib.adapter.openoffice.OpenOfficeAdapter.processEntry(OpenOfficeAdapter.java:116)
    at nz.govt.natlib.adapter.openoffice.OpenOfficeAdapter.adapt(OpenOfficeAdapter.java:91)
    at edu.harvard.hul.ois.fits.tools.nlnz.MetadataExtractor.extractInfo(MetadataExtractor.java:95)
    at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:275)
    at java.lang.Thread.run(Thread.java:744)

**Comment by daveneiman** [comment]
Yes, we have seen this problem, too. It turns out the exception is thrown from within the NLNZ Metadata Extractor tool embedded within FITS. This tool is out of our control. However, the exception does not stop the other tools within FITS from processing ODT files.
