### ISSUE TITLE
Using xercesImpl-2.x.x.jar above version 2.9.1 throws exception exception  java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by cudevmaxwell** [harvard-lts/fits#256]
When using fits-1.5.1, we ran into this exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
       at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source)
       at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
       at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
       at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source)
       at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
       at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
       at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
       at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
       at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
       at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:942)
       at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:908)
       at org.apache.commons.configuration.XMLConfiguration$XMLFileConfigurationDelegate.load(XMLConfiguration.java:1584)
       at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:324)
       at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:261)
       at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
       at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.load(AbstractHierarchicalFileConfiguration.java:184)
       at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.<init>(AbstractHierarchicalFileConfiguration.java:95)
       at org.apache.commons.configuration.XMLConfiguration.<init>(XMLConfiguration.java:259)
       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:199)
       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:124)
       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:113)
       at edu.harvard.hul.ois.fits.Fits.constructFits(Fits.java:348)
       at edu.harvard.hul.ois.fits.Fits.main(Fits.java:326)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
       at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
       ... 35 more
```

Replacing `lib/xercesImpl-2.12.1.jar` with `lib/xercesImpl-2.9.1.jar` fixes the problem, FITS can run without firing the exception. 

Environment: RHEL 8.5, openjdk version 1.8.0_322.

**Comment by daveneiman** [comment]
Updated in dev branch and will be in upcoming release.
