### ISSUE TITLE
Error in jhove_common_to_fits.xslt (FITS 0.6.3)

### ISSUE THREAD

**Issue by techmaurice** [harvard-lts/fits#3]
When analyzing TIFF files, the following error keeps occuring
<code>
Error on line 194 of jhove_common_to_fits.xslt:
  XPTY0004: A sequence of more than one item is not allowed as the first argument of concat()
  at xsl:for-each (file:/github/fits/xml/jhove/jhove_common_to_fits.xslt#188)
     processing /repInfo/properties[1]/property[1]/values[1]/property[3]/values[
1]/value[1]
edu.harvard.hul.ois.fits.exceptions.FitsToolException: Jhove: Error converting output using \github\fits\xml\jhove\jhove_image_to_fits.xslt (A sequence of more
than one item is not allowed as the first argument of concat())
        at edu.harvard.hul.ois.fits.tools.ToolBase.transform(ToolBase.java:115)
        at edu.harvard.hul.ois.fits.tools.jhove.Jhove.extractInfo(Jhove.java:153
)
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:192)
        at java.lang.Thread.run(Unknown Source)
</code>

**Comment by daveneiman** [comment]
FITS code has changed significantly since this issue was created. If you could provide a TIFF file that recreates this issue on the current version of FITS it will be considered. Otherwise, the issue will be closed. Thank you.
