### ISSUE TITLE
Running fits.sh throws "Failed to instantiate SLF4J LoggerFactory" in 1.5.2 release

### ISSUE THREAD

**Issue by bbarberBPL** [harvard-lts/fits#316]
I just updated to the recent 1.5.2 release locally and tried testing it using a bash shell (ie: `/path/to/fits/fits.sh -i /path/to/file.tif`) and it it now throwing the error in the title. I verified my `$FITS_HOME` environment variable is still pointing to the correct folder and all the jars get appended to the `$APPCLASSPATH` in `fits-env.sh`. Here is the full stack trace I captured. 

```
java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/AbstractLoggerAdapter
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)

        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:36)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:162)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:125)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:114)
        at edu.harvard.hul.ois.fits.Fits.constructFits(Fits.java:317)
        at edu.harvard.hul.ois.fits.Fits.main(Fits.java:295)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.spi.AbstractLoggerAdapter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 20 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/AbstractLoggerAdapter
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)

        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:36)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:162)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:125)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:114)
        at edu.harvard.hul.ois.fits.Fits.constructFits(Fits.java:317)
        at edu.harvard.hul.ois.fits.Fits.main(Fits.java:295)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.spi.AbstractLoggerAdapter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 20 more
```

My machine/environment specs are
```
OS: Pop!_OS 20.04
Java version: openjdk version "11.0.15" 2022-04-19
```

**Comment by cudevmaxwell** [comment]
Running into this issue as well. Adding `log4j-api-2.17.2.jar` and `log4j-core-2.17.2.jar` to the libs directory fixes this issue... but then returns `Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal`, meaning https://github.com/harvard-lts/fits/issues/256 isn't actually resolved.

**Comment by daveneiman** [comment]
Will have an update for this shortly. The exception was being thrown when running FITS in Java 8 but not Java 11.

**Comment by cudevmaxwell** [comment]
Really appreciate the update and your work, thanks @daveneiman.

**Comment by daveneiman** [comment]
Hello - please check out this 1.5.3 release. I should resolve the above problems when running under Java 8.
https://github.com/harvard-lts/fits/releases/tag/1.5.3

**Comment by cudevmaxwell** [comment]
The new release (1.5.3) is working great in our environment. Tested with a manual run and from our Hyrax based IR stack. Thanks again @daveneiman!

**Comment by daveneiman** [comment]
@cudevmaxwell Turns out we've identified that this release, which upgraded to log4j2, still contains log4j (1) jar files within Tika and Droid. Will be trying to sort out the implications.

**Comment by bbarberBPL** [comment]
The release(1.5.3) is working on my end now too(both via terminal and my through my rails app). Thanks for the quick fix @daveneiman!

**Comment by pwinckles** [comment]
@daveneiman Why did you remove the log4j2 dependencies in this commit: https://github.com/harvard-lts/fits/commit/519a4ab372ebbeee7b2581b2de0897a9e87ffe1a

Those are _required_ for the logging to work. The main branch does not currently work.

**Comment by daveneiman** [comment]
This has been fixed in in the main branch.
