### ISSUE TITLE
Exception NoClassDefFoundError in FITS 1.5.1 in Windows 10 64 bits with Java 1.8.0

### ISSUE THREAD

**Issue by RvanVeenendaal** [harvard-lts/fits#325]
Hi,

Today we wanted to show an intern how to use FITS.
We downloaded fresh copies of 1.5.1 from your site to our laptops.
We then ran the following command, with the following result.
Something related the Xerces library used?
What to do?

C:\Temp\fits-1.5.1>fits.bat  -i C:\Temp -o C:\Temp
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source)
        at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source)
        at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:942)
        at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:908)
        at org.apache.commons.configuration.XMLConfiguration$XMLFileConfigurationDelegate.load(XMLConfiguration.java:1584)
        at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:324)
        at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:261)
        at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
        at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.load(AbstractHierarchicalFileConfiguration.java:184)
        at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.<init>(AbstractHierarchicalFileConfiguration.java:95)
        at org.apache.commons.configuration.XMLConfiguration.<init>(XMLConfiguration.java:259)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:199)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:124)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:113)
        at edu.harvard.hul.ois.fits.Fits.constructFits(Fits.java:348)
        at edu.harvard.hul.ois.fits.Fits.main(Fits.java:318)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 35 more

**Comment by awoods** [comment]
Can you try the most recent release, 1.5.5: https://github.com/harvard-lts/fits/releases/tag/1.5.5

**Comment by awoods** [comment]
Resolved with: https://github.com/harvard-lts/fits/commit/a6800c34034e054e237182bac35cfbc5fed84e19 (Release 1.5.5)
