### ISSUE TITLE
Same NLNZ Metadata Extractor error appears in every error message

### ISSUE THREAD

**Issue by RvanVeenendaal** [harvard-lts/fits#332]
Hi,

When I run FITS 1.5.5 against the OPF File Format Corpus (downloaded this week), I see the same NLNZ Metadata Extractor message in the console output again and again, after it appeared the first time. A console output fragment is included below. I would expect that this NLNZ message appears only once, when the problematic file is being processed. Not at every subsequent error message. I'm running FITS on an Intel Xeon Gold 6148 CPU 2.40 GHz 8GM RAM 64 bits Windows 10 machine.

...
2022-09-29 20:25:43 - ERROR - Fits:677 - Tool error processing file: 344.xml
NLNZ Metadata Extractor error while harvesting file simple-open-password.pdf (Error: The supplied password does not match either the owner or user password in the document.)
edu.harvard.hul.ois.fits.exceptions.FitsToolException: NLNZ Metadata Extractor error while harvesting file simple-open-password.pdf (Error: The supplied password does not match either the owner or user password in the document.)
        at edu.harvard.hul.ois.fits.tools.nlnz.MetadataExtractor.extractInfo(MetadataExtractor.java:115)
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:284)
        at java.lang.Thread.run(Unknown Source)
2022-09-29 20:25:44 - ERROR - Fits:677 - Tool error processing file: 345.xml
Exiftool: Error converting output using C:\XXXXXXXXXX\fits-1.5.5\xml\exiftool\exiftool_text_to_fits.xslt (A sequence of more than one item is not allowed as the first argument of fn:concat() (<FileType/>, <FileType/>) )
edu.harvard.hul.ois.fits.exceptions.FitsToolException: Exiftool: Error converting output using C:\Users\rvveenendaal\Tools\fits-c3po\FITS\fits-1.5.5\xml\exiftool\exiftool_text_to_fits.xslt (A sequence of more than one item is not allowed as the first argument of fn:concat() (<FileType/>, <FileType/>) )
        at edu.harvard.hul.ois.fits.tools.ToolBase.transform(ToolBase.java:149)
        at edu.harvard.hul.ois.fits.tools.exiftool.Exiftool.extractInfo(Exiftool.java:152)
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:284)
        at java.lang.Thread.run(Unknown Source)
2022-09-29 20:25:44 - ERROR - Fits:677 - Tool error processing file: 345.xml
NLNZ Metadata Extractor error while harvesting file simple-open-password.pdf (Error: The supplied password does not match either the owner or user password in the document.)
edu.harvard.hul.ois.fits.exceptions.FitsToolException: NLNZ Metadata Extractor error while harvesting file simple-open-password.pdf (Error: The supplied password does not match either the owner or user password in the document.)
        at edu.harvard.hul.ois.fits.tools.nlnz.MetadataExtractor.extractInfo(MetadataExtractor.java:115)
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:284)
        at java.lang.Thread.run(Unknown Source)
...

**Comment by pwinckles** [comment]
@RvanVeenendaal Thanks for the report. The problem of exceptions carrying over to other files has been addressed here https://github.com/harvard-lts/fits/issues/206 and will be fixed in the 1.6.0 release, which should be coming soon.

Are you concerned about any of the exceptions themselves, or just that they were carrying over between files?

**Comment by RvanVeenendaal** [comment]
Concern was due to carrying over in general.
Thanks, Remco

**Comment by pwinckles** [comment]
Great. I'm going to close this out then. Will be fixed in the next release.
