### ISSUE TITLE
OIS Audio Information tool fails to run on .wav files in FITS 1.6.0

### ISSUE THREAD

**Issue by paul-aloisio** [harvard-lts/fits#366]
When running FITS 1.6.0 against .wav files, I get the error below on the console.  The statistics section of the fits output shows that the OIS Audio Information tool failed to run.  Without the OIS Audio Information tool, crucial information, such as duration, is excluded from FITS output

C:\Program Files\fits-1.6.0-SNAPSHOT_A>fits.bat -xc -i E:\FITS\FITS_Test_Files\experiments\audio_file_test -o E:\FITS\FITS_Test_Files\experiments\audio_file_test
2022-12-15 15:54:22 - ERROR - Fits:684 - Tool error processing file: T-257_146_PM_01_01_{F434A014-E918-4E41-8D52-810D5887E924}.wav
edu/harvard/hcl/hclaps/util/ByteConvertor
java.lang.NoClassDefFoundError: edu/harvard/hcl/hclaps/util/ByteConvertor
        at edu.harvard.hul.ois.fits.tools.oisfileinfo.AudioInfo.tasteMagicNumber(AudioInfo.java:190) ~[fits-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at edu.harvard.hul.ois.fits.tools.oisfileinfo.AudioInfo.createXml(AudioInfo.java:79) ~[fits-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at edu.harvard.hul.ois.fits.tools.oisfileinfo.AudioInfo.extractInfo(AudioInfo.java:60) ~[fits-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:271) ~[fits-1.6.0-SNAPSHOT.jar:1.6.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.ClassNotFoundException: edu.harvard.hcl.hclaps.util.ByteConvertor
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 5 more
[T-257_146_PM_01_01_{F434A014-E918-4E41-8D52-810D5887E924}.zip](https://github.com/harvard-lts/fits/files/10240621/T-257_146_PM_01_01_.F434A014-E918-4E41-8D52-810D5887E924.zip)

**Comment by pwinckles** [comment]
The problem is that the hclaps jar was accidentally removed here: https://github.com/harvard-lts/fits/commit/37e5568dbbcdd0b87bc81a92fb8b0ff43a786b0d

**Comment by paul-aloisio** [comment]
The new update resolved this issue
