### ISSUE TITLE
FITS 1.6.0 does not have a mediainfo library for the ARM Mac’s

### ISSUE THREAD

**Issue by awoods** [harvard-lts/fits#389]
/Applications/fits/fits.sh -x -i /Volumes/mediapres2/globus_dropbox/Memnon/Memnon-Batch-06/BATCH_0005/DEPOSIT_230705145315/32044160172193/archival/32044160172193_AM_01_01.mov -o /Volumes/mediapres2/globus_dropbox/Memnon/Memnon-Batch-06/BATCH_0005/DEPOSIT_230705145315/32044160172193/archival/32044160172193_AM_01_01_test.xml   
2023-08-21 13:30:19 - ERROR - MediaInfo:95 - Error loading native library for this operating system for tool: MediaInfo. ostype=[MacOS] -- jvmModel=[64] -- nativeLibPath=[/Applications/fits/tools/mediainfo/mac] -- No native MediaInfo library for this OS
java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/gh/gszlyl290h1dnlk8t2_th5s80000gp/T/jna-2040574825/jna16480843601716805071.tmp
       at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
       at java.base/java.lang.Runtime.load0(Runtime.java:768)
       at java.base/java.lang.System.load(System.java:1850)
       at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
       at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
       at com.sun.jna.Native.<clinit>(Native.java:131)
       at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfoNativeWrapper$MediaInfoDLL_Internal.<clinit>(MediaInfoNativeWrapper.java:101)
       at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfoNativeWrapper.Option_Static(MediaInfoNativeWrapper.java:442)
       at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.<init>(MediaInfo.java:86)
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
       at edu.harvard.hul.ois.fits.tools.ToolBelt.createToolClassInstance(ToolBelt.java:169)
       at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:122)
       at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:58)
       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:244)
       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:124)
       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:113)
       at edu.harvard.hul.ois.fits.Fits.constructFits(Fits.java:348)
       at edu.harvard.hul.ois.fits.Fits.main(Fits.java:326)
2023-08-21 13:30:19 - ERROR - ToolBelt:139 - Thread [1] Error instantiating class: edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo -- Exception thrown: java.lang.InstantiationException -- Error message: edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo

**Comment by pwinckles** [comment]
@awoods I think there's something else going on here. I just downloaded 1.6.0 and ran it on a M1 and MediaInfo works as expected. In fact, the MediaInfo lib for x86_64 and arm64 is identical: https://mediaarea.net/en/MediaInfo/Download/Mac_OS

**Comment by pwinckles** [comment]
> @pwinckles : Running FITS on a Mac ARM works for you?

Yes, that's correct

**Comment by kaylieackerman** [comment]
@pwinckles Are you running Ventura 13.4.1?

**Comment by kaylieackerman** [comment]
FWIW, media info itself runs fine on this machine. I redownloaded fits and I am getting a slightly different stack trace (below). I think I was 1 version back this morning. This machine is running a native java 11 install through brew.

openjdk 11.0.20 2023-07-18
OpenJDK Runtime Environment Homebrew (build 11.0.20+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.20+0, mixed mode)

$echo $JAVA_HOME 
/opt/homebrew/Cellar/openjdk@11/11.0.20/libexec/openjdk.jdk/Contents/Home

Here is the stack trace

./fits.sh -x -i /Volumes/mediapres2/VIDEO/FY24/Divinity/Pearson_Batch_03/6/DEPOSIT_230405180848/32044160156444/archival/32044160156444_AM_01_01.mov  -o /Volumes/mediapres2/VIDEO/FY24/Divinity/Pearson_Batch_03/6/DEPOSIT_230405180848/32044160156444/archival/32044160156444_AM_01_01_test.xml 
2023-08-21 16:08:17 - ERROR - ToolBelt:140 - Thread 1 error initializing edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo: java.lang.InstantiationException  Message: edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo
java.lang.InstantiationException: edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo
	at java.base/java.lang.Class.newInstance(Class.java:571)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.createToolClassInstance(ToolBelt.java:174)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:122)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:58)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:243)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:123)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:112)
	at edu.harvard.hul.ois.fits.Fits.constructFits(Fits.java:325)
	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:307)
Caused by: java.lang.NoSuchMethodException: edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	... 8 more

**Comment by kaylieackerman** [comment]
This might be the issue. Media info is only x86  and java is ARM.

'If the running JDK targets aarch64 (ARM), the architecture used by an M1 Mac, then an UnsatisfiedLinkError is thrown at startup. There is no native ARM build of TypeDB yet, so in order for TypeDB to run correctly on an M1 MacBook you need to ensure that a JDK that targets x64 architecture is installed.'

https://stackoverflow.com/questions/71237976/unsatisfiedlinkerror-when-running-typedb-on-an-m1-macbook

I could try installing an x86 java and see, though that seems like a stupid thing to have to do.

**Comment by pwinckles** [comment]
@kaylieackerman I was able to run it on a M1 OS 13.1 (22C65) (so, different version than you), using java 17 (arm build) (I'll try with java 11 in a minute).

The development version of FITS has the latest release of MediaInfo in it, you could try build it, and seeing if that works for you.

```java
mvn -DskipTests clean package
```

That should produce a zip file at `target/fits-1.6.1-SNAPSHOT.zip` that you could try.

**Comment by pwinckles** [comment]
Yes, it worked for me with java 11 as well.

**Comment by pwinckles** [comment]
If you don't feel like figuring out why it's not working on your system, you could just install mediainfo at the system level and delete `tools/mediainfo` in you FITS install

**Comment by kaylieackerman** [comment]
I wish it were so simple, but that also didn't work.

**Comment by awoods** [comment]
It seems like we can document this as a known issue when run in a mixed architecture environment, then close this ticket. Does that sound right to you @kaylieackerman and @pwinckles ?

**Comment by pwinckles** [comment]
@awoods @kaylieackerman : I don't understand what the problem is here. I use [sdkman](https://sdkman.io/) to manage/install java versions, so it's possible that there's something wrong with the brew version. I don't know haven't tried it. On my machine, it works with both an arm64 build and x86_64 build. Maybe it's related to the OS version? I don't know. I don't feel like upgrading right now to test it as that can be a can of worms.

My installs:

```
file $JAVA_HOME/bin/javac
/Users/peter.winckles/.sdkman/candidates/java/current/bin/javac: Mach-O 64-bit executable arm64

file $JAVA_HOME/bin/javac
/Users/peter.winckles/.sdkman/candidates/java/17.0.4-amzn-x86/bin/javac: Mach-O 64-bit executable x86_64
```

It's not possible to install x84_64 builds through sdkman. That version I installed manually.

**Comment by kaylieackerman** [comment]
Can you try a clean install of fits-latest.zip from https://projects.iq.harvard.edu/fits/downloads and running that against the arm64 java you have installed and see if that works using the included media info libraries?

Kaylie

On Aug 21, 2023, at 6:33 PM, Peter Winckles ***@***.***> wrote:

﻿

@awoods<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_awoods&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=md69f6KgtDeomOT4bYCi2Pa7txIIOYIbRWeAOSrba-U&m=DKKL2Jm-a1WhLp9pUpFHb9cXclHt4F8LEvAfTdMAJ-z69irTXxwQo0GhMwUgygWd&s=SylXURpWABO3u_4aU_irC0mRk4QA2KauTgUV9b-ah00&e=> @kaylieackerman<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kaylieackerman&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=md69f6KgtDeomOT4bYCi2Pa7txIIOYIbRWeAOSrba-U&m=DKKL2Jm-a1WhLp9pUpFHb9cXclHt4F8LEvAfTdMAJ-z69irTXxwQo0GhMwUgygWd&s=30Hg8LuLfNuTlqrg2dpVjFcyFAeL2BAjvrIBX7J90OM&e=> : I don't understand what the problem is here. I use sdkman<https://urldefense.proofpoint.com/v2/url?u=https-3A__sdkman.io_&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=md69f6KgtDeomOT4bYCi2Pa7txIIOYIbRWeAOSrba-U&m=DKKL2Jm-a1WhLp9pUpFHb9cXclHt4F8LEvAfTdMAJ-z69irTXxwQo0GhMwUgygWd&s=4xOasTfvkKmCQXVWeD8B3_QWeScbBCEazdNYJXr9PkY&e=> to manage/install java versions, so it's possible that there's something wrong with the brew version. I don't know haven't tried it. On my machine, it works with both an arm64 build and x86_64 build. Maybe it's related to the OS version? I don't know. I don't feel like upgrading right now to test it as that can be a can of worms.

My installs:

file $JAVA_HOME/bin/javac
/Users/peter.winckles/.sdkman/candidates/java/current/bin/javac: Mach-O 64-bit executable arm64

file $JAVA_HOME/bin/javac
/Users/peter.winckles/.sdkman/candidates/java/17.0.4-amzn-x86/bin/javac: Mach-O 64-bit executable x86_64


It's not possible to install x84_64 builds through sdkman. That version I installed manually.

**Comment by pwinckles** [comment]
@kaylieackerman the fits-latest link on that page is for version 1.4.0. This is the correct place to download 1.6.0: https://github.com/harvard-lts/fits/releases/tag/1.6.0

**Comment by kaylieackerman** [comment]
That page is the first that comes up in a Google search (for me). Someone should update the link. Does the 1.6 release have a newer mediainfo?



From: Peter Winckles ***@***.***>
Date: Monday, August 21, 2023 at 9:11 PM
To: harvard-lts/fits ***@***.***>
Cc: Ackerman, Kaylie Alannah ***@***.***>, Mention ***@***.***>
Subject: Re: [harvard-lts/fits] FITS 1.6.0 does not have a mediainfo library for the ARM Mac’s (Issue #389)

@kaylieackerman<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kaylieackerman&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=md69f6KgtDeomOT4bYCi2Pa7txIIOYIbRWeAOSrba-U&m=7vVm6Y9CbQ0hAYXXVLQY_Ch5UgfsuxKwb5TYKqFOnzOyxmnZIcASiBD-h-WECIKK&s=_bb6WdSMABaPIg7Dsz9-V6ft0E5wdjI6lgrc5XVJkHI&e=> the fits-latest link on that page is for version 1.4.0. This is the correct place to download 1.6.0: https://github.com/harvard-lts/fits/releases/tag/1.6.0<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_harvard-2Dlts_fits_releases_tag_1.6.0&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=md69f6KgtDeomOT4bYCi2Pa7txIIOYIbRWeAOSrba-U&m=7vVm6Y9CbQ0hAYXXVLQY_Ch5UgfsuxKwb5TYKqFOnzOyxmnZIcASiBD-h-WECIKK&s=JDtk1xKjhFBgMkUttZcbKbGJkG6V5rbLuJ62zjOHIZU&e=>

**Comment by pwinckles** [comment]
@kaylieackerman Yes, the version of MediaInfo in 1.4.0 is extremely old. 1.6.0 is using MediaInfo 22.09

**Comment by kaylieackerman** [comment]
Peter,

Using 1.6 with an ARM java I am now getting an error loading Jpylyzer. I’m not even sure what that is. Any thoughts on why this is killing the analysis of a video file with mediainfo?

Kaylie


~$./fits.sh -x -i /Volumes/mediapres2/VIDEO/FY24/Divinity/Pearson_Batch_03/6/DEPOSIT_230405180848/32044160156444/archival/32044160156444_AM_01_01.mov  -o /Volumes/mediapres2/VIDEO/FY24/Divinity/Pearson_Batch_03/6/DEPOSIT_230405180848/32044160156444/archival/32044160156444_AM_01_01_test.xml

2023-08-22 12:40:52 - ERROR - Jpylyzer:76 - Python and Windows not supported, not running jpylyzer

2023-08-22 12:40:52 - ERROR - ToolBelt:144 - Thread [1] Error instantiating class: edu.harvard.hul.ois.fits.tools.jpylyzer.Jpylyzer -- Exception thrown: java.lang.reflect.InvocationTargetException -- Error message: null

2023-08-22 12:43:15 - ERROR - Fits:684 - Tool error processing file: 32044160156444_AM_01_01.mov

null

java.lang.reflect.InvocationTargetException: null

       at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?]

       at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]

       at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]

       at edu.harvard.hul.ois.fits.tools.ToolBelt.createToolClassInstance(ToolBelt.java:174) ~[fits-1.6.0.jar:1.6.0]

       at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:127) ~[fits-1.6.0.jar:1.6.0]

       at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:56) ~[fits-1.6.0.jar:1.6.0]

       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:231) ~[fits-1.6.0.jar:1.6.0]

       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:129) ~[fits-1.6.0.jar:1.6.0]

       at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:118) ~[fits-1.6.0.jar:1.6.0]

       at edu.harvard.hul.ois.fits.Fits.constructFits(Fits.java:341) ~[fits-1.6.0.jar:1.6.0]

       at edu.harvard.hul.ois.fits.Fits.main(Fits.java:315) ~[fits-1.6.0.jar:1.6.0]

Caused by: edu.harvard.hul.ois.fits.exceptions.FitsToolException: jpylyzer cannot be used on this system

       at edu.harvard.hul.ois.fits.tools.jpylyzer.Jpylyzer.<init>(Jpylyzer.java:77) ~[fits-1.6.0.jar:1.6.0]

       at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]

       ... 10 more



From: Peter Winckles ***@***.***>
Date: Monday, August 21, 2023 at 9:52 PM
To: harvard-lts/fits ***@***.***>
Cc: Ackerman, Kaylie Alannah ***@***.***>, Mention ***@***.***>
Subject: Re: [harvard-lts/fits] FITS 1.6.0 does not have a mediainfo library for the ARM Mac’s (Issue #389)

@kaylieackerman<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kaylieackerman&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=md69f6KgtDeomOT4bYCi2Pa7txIIOYIbRWeAOSrba-U&m=CQpJtDntBdWF6SYI43W8U3QsN5j_bwiy-by1UHeXVss7z0drFdOz82et_bGPcAPV&s=U2ulZ_bBtT-ZWxDdMMci2Dylxz1qlFXsASSxH1BxTVM&e=> Yes, the version of MediaInfo in 1.4.0 is extremely old. 1.6.0 is using MediaInfo 22.09

**Comment by pwinckles** [comment]
@kaylieackerman You need to either install Python or disable Jpylyzer in the fits.xml

**Comment by kaylieackerman** [comment]
Python is installed but it is python3. I disabled the option in fits.xml.

From: Peter Winckles ***@***.***>
Date: Tuesday, August 22, 2023 at 12:56 PM
To: harvard-lts/fits ***@***.***>
Cc: Ackerman, Kaylie Alannah ***@***.***>, Mention ***@***.***>
Subject: Re: [harvard-lts/fits] FITS 1.6.0 does not have a mediainfo library for the ARM Mac’s (Issue #389)

@kaylieackerman<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kaylieackerman&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=md69f6KgtDeomOT4bYCi2Pa7txIIOYIbRWeAOSrba-U&m=vcfDjlb5vXxOmjjYO77b-wEOCofi0oIbQkuqSOmWAke5lj1fby9HoHWnFTqBY89w&s=i0g_MU_sdEKqcJZf6G6afexy1d1QZAWw-ovsa_CxBeU&e=> You need to either install Python or disable Jpylyzer in the fits.xml

**Comment by awoods** [comment]
@kaylieackerman : In case you want to take advantage of Jpylyzer in the future, here are instructions for having Python recognized by FITS:
[bb2_4_mac_python_plus_security.docx](https://github.com/harvard-lts/fits/files/12414194/bb2_4_mac_python_plus_security.docx)
