### ISSUE TITLE
Issue running FITS on Mac M1 - Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by mutanthumb** [harvard-lts/fits#396]
Hi-
I can't seem to get past this error.  I also tried building FITS 1.6 but kept getting the "missing main" issue.  Any advice would be greatly appreciated. I'm trying compare FITS results outside of Archivematica with issues I'm seeing in Archivematica.

Thanks,
susan

Here is my Java info:
```
sborda@m-g6lpg47kn4 ~ % java -version
openjdk version "1.8.0_422"
OpenJDK Runtime Environment Corretto-8.422.05.1 (build 1.8.0_422-b05)
OpenJDK 64-Bit Server VM Corretto-8.422.05.1 (build 25.422-b05, mixed mode)
```

```
sborda@m-g6lpg47kn4 ~ % fits -i /Users/sborda/Downloads/image1.jpeg 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/harvard/hul/ois/fits/Fits has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
```

**Comment by pwinckles** [comment]
FITS requires java 11 or greater

**Comment by mutanthumb** [comment]
I was going by this on your site:Sent from my iPhoneOn Aug 14, 2024, at 4:19 PM, Peter Winckles ***@***.***> wrote:﻿
FITS requires java 11 or greater
